language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.0
          env: deps=lowest
        - php: 7.1
        - php: 7.2
        - php: 7.3

install:
    - if [ -z "$deps" ]; then composer install; fi;
    - if [ "$deps" = "lowest" ]; then composer update --prefer-lowest -n; fi;
    
script: vendor/bin/phpunit
